Add example of auto-instrumenting Python Flask application using OpenTelemetry
last9/opentelemetry-examples pull request #4
Opened 2024-07-12 12:34 UTC by chtushar

- Adds example to demonstrate flask instrumentation with OTel

2024-07-14 15:05 UTC, prathamesh-sonpatki requested changes

2024-07-14 15:05 UTC, prathamesh-sonpatki commented on python/with-flask/run.sh
> +export $(grep -v '^#' .env | xargs)
https://github.com/open-telemetry/opentelemetry-python/issues/3189#issuecomment-1769264773

2024-07-14 15:05 UTC, prathamesh-sonpatki commented
@chtushar Please change PR title to

Add example of auto-instrumenting Python Flask application using OpenTelemetry

2024-07-15 18:37 UTC, chtushar commented on python/with-flask/README.md
> +- Give permission to execute the `run.sh` script:
`run.sh` is required to load the environment variables.

2024-07-16 09:05 UTC, prathamesh-sonpatki commented on python/flask/README.md
> +> basic authorization header.
```suggestion
> basic authorization header. Read this post to know how [Python Otel SDK](https://last9.io/blog/whitespace-in-otlp-headers-and-opentelemetry-python-sdk/) handles whitespace in headers for more details.
```

2024-07-16 09:08 UTC, prathamesh-sonpatki commented on python/flask/README.md
> +export OTEL_TRACES_EXPORTER=console,otlp
```suggestion
export OTEL_TRACES_EXPORTER=otlp
```

2024-07-16 10:26 UTC, prathamesh-sonpatki approved these changes

2024-07-16 10:26 UTC, merged