Add ruby on rails example instrumented using OpenTelemetry
last9/opentelemetry-examples pull request #5
Opened 2024-07-16 19:39 UTC by chtushar

2024-07-20 15:02 UTC, prathamesh-sonpatki requested changes

2024-07-20 15:02 UTC, prathamesh-sonpatki commented on ruby/rails-api/README.md
> +   API endpoints are:
```suggestion
6. Once the server is running, you can access the application at
   `http://localhost:3000` by default. The
   API endpoints are:
```

2024-07-20 15:02 UTC, prathamesh-sonpatki commented on ruby/rails-api/README.md
> +
Step 5 should be how to configured in the `config/initializers/opentelemetry.rb`

```
require 'opentelemetry/sdk'
require 'opentelemetry/exporter/otlp'
require 'opentelemetry/instrumentation/all'

OpenTelemetry::SDK.configure do |c|
  c.service_name = 'ruby-on-rails-api-service'

  config = {'OpenTelemetry::Instrumentation::fs' => { enabled: false }}
  c.use_all(config) # enables all instrumentation!
end
```

2024-07-20 15:10 UTC, prathamesh-sonpatki requested changes

2024-07-20 15:10 UTC, prathamesh-sonpatki commented on ruby/rails-api/.env.example.erb
> +OTEL_METRICS_EXPORTER=otlp
@chtushar if this option is not used, please remove it.

2024-07-20 15:10 UTC, prathamesh-sonpatki commented on ruby/rails-api/config/initializers/opentelemetry.rb
> +  config = {'OpenTelemetry::Instrumentation::fs' => { enabled: false }}
@chtushar Have you verified this config is true? I checked [here](https://github.com/open-telemetry/opentelemetry-ruby-contrib/tree/main/instrumentation), there is no `fs` instrumentation for Ruby.

2024-07-21 17:10 UTC, chtushar commented on ruby/rails-api/README.md
> +4. In the `.env` file, set the value of `OTEL_EXPORTER_OTLP_HEADERS` to the OTLP
<img width="990" alt="Screenshot 2024-07-21 at 10 36 32 PM" src="https://github.com/user-attachments/assets/b0df73ad-dfb5-450c-8b2f-4689cf568321">

Not copy pasted. It is duly checked. It works with the encoding. The traces in "traces.png" are captured after following the instructions in the README.md file.

2024-07-21 17:14 UTC, chtushar commented on ruby/rails-api/README.md
> +
We are doing that in the docs. The README.md is a guide to set up this example.

2024-07-25 07:28 UTC, prathamesh-sonpatki commented on ruby/rails-api/README.md
> +4. In the `.env` file, set the value of `OTEL_EXPORTER_OTLP_HEADERS` to the OTLP
@chtushar Does it work without encoding?

2024-08-04 18:48 UTC, prathamesh-sonpatki commented on ruby/rails-api/README.md
> +4. In the `.env` file, set the value of `OTEL_EXPORTER_OTLP_HEADERS` to the OTLP
@chtushar Please respond to this.

2024-08-04 18:55 UTC, prathamesh-sonpatki approved these changes

2024-08-04 18:55 UTC, merged