Add example of auto-instrumenting Sinatra application using OpenTelemetry
last9/opentelemetry-examples pull request #6
Opened 2024-07-18 08:30 UTC by chtushar

- Add example of auto-instrumenting Sinatra application using OpenTelemetry

2024-07-20 15:09 UTC, prathamesh-sonpatki requested changes

2024-07-20 15:09 UTC, prathamesh-sonpatki commented on ruby/sinatra/README.md
> +
@chtushar Add a point here about checking `instrumentation.rb` and how it is included in the `app.rb`

2024-07-20 15:09 UTC, prathamesh-sonpatki commented on ruby/sinatra/instrumentation.rb
> +  config = {'OpenTelemetry::Instrumentation::fs' => { enabled: false }}
@chtushar Have you verified this config is true? I checked here, there is no `fs` instrumentation for Ruby.

2024-07-21 17:37 UTC, chtushar commented on ruby/sinatra/README.md
> +
@prathamesh-sonpatki We do that in the `docs`. The purpose of this README.md is how to setup the example.

2024-08-29 13:31 UTC, merged